version: '3.4'

services:
  samuraibackend:
    image: samuraibackend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    networks:
      - samurai-backend_default
