version: '3.7'

services:
  # Django application
  web:
    build:
      context: .
      dockerfile: backend.dockerfile
    volumes:
      - type: bind
        source: ./
        target: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  # PostgreSQL database
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgresData:/var/lib/postgresql/data

  # Redis server
  redis:
    image: "redis:latest"
    volumes:
      - redisData:/data

  # Celery worker
  worker:
    build:
      context: .
      dockerfile: worker.dockerfile
    volumes:
      - type: bind
        source: ./
        target: /app
    depends_on:
      - db
      - redis
  
  beat:
    build:
      context: .
      dockerfile: beat.dockerfile
    volumes:
      - type: bind
        source: ./
        target: /app
    depends_on:
      - db
      - redis

  # Swagger UI for documentation; Disabled for now
  # swagger:
  #   image: swaggerapi/swagger-ui
  #   environment:
  #     - URL=${BASE_URL}/swagger.json
  #   ports:
  #     - "8080:8080"

volumes:
  postgresData:
  redisData: