# Generated by Django 5.0.2 on 2024-03-10 18:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_alter_chat_options_alter_message_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='id',
            new_name='chat_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='id',
            new_name='message_id',
        )
    ]
