# Generated by Django 5.0 on 2024-01-15 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_baseuser_created_at_alter_baseuser_updated_at_and_more'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='userproject',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Project', 'verbose_name_plural': 'User Projects'},
        ),
        migrations.AlterModelOptions(
            name='usertask',
            options={'ordering': ['order'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='comments', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='text content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to='accounts.student', verbose_name='related student'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to='accounts.teacher', verbose_name='related supervisor'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='tasks',
            field=models.ManyToManyField(related_name='user_projects', to='students.usertask', verbose_name='related tasks'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='theme',
            field=models.CharField(max_length=255, verbose_name='theme'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='students.comment', verbose_name='related comments'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='due_date',
            field=models.DateField(blank=True, help_text='The date when this task should be completed', null=True, verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='name',
            field=models.CharField(max_length=255, verbose_name='task name'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='order',
            field=models.IntegerField(verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='The teacher who will review this task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='accounts.teacher', verbose_name='related reviewer'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('in_review', 'In review'), ('reopened', 'Reopened'), ('done', 'Done')], default='new', max_length=255, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
