# Generated by Django 5.0 on 2024-01-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_comment_options_alter_userproject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
