# Generated by Django 5.0 on 2024-01-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_comment_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='file_name',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='text content'),
        ),
    ]
