# Generated by Django 5.0 on 2023-12-14 20:14

import accounts.models.base_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='registration_code',
            field=models.CharField(default=accounts.models.base_user.generate_registration_code, max_length=150, null=True, verbose_name='registration code'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(default=accounts.models.base_user.generate_default_email, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
