# Generated by Django 5.0 on 2023-12-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_squashed_0003_baseuser_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={'verbose_name': 'Base User', 'verbose_name_plural': 'base users'},
        ),
        migrations.AlterModelOptions(
            name='overseer',
            options={'verbose_name': 'Overseer', 'verbose_name_plural': 'Overseers'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
    ]
