# Generated by Django 5.0 on 2024-01-15 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_baseuser_options_alter_overseer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='faculty name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounts.faculty', verbose_name='related faculty'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name of the group'),
        ),
        migrations.AlterField(
            model_name='overseer',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overseers', to='accounts.faculty', verbose_name='related faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.group', verbose_name='related group'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contact_information',
            field=models.TextField(blank=True, null=True, verbose_name='contact information'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='faculties',
            field=models.ManyToManyField(related_name='teachers', to='accounts.faculty', verbose_name='related faculties'),
        ),
    ]
