name: samurai-backend

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: DevDB
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
