version: "3.8"

name: samurai-backend

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: DevDB
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

  celery:
    image: samurai-backend
    entrypoint: ["/app/celery.sh"]
    depends_on:
      - database
      - redis

  web:
    image: samurai-backend
    entrypoint: ["/app/web.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis

volumes:
  postgres-data:
  redis-data: