name: samurai-backend

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: DevDB
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  db-viewer:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: mail@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
