"""User Projects and Tasks

Revision ID: 07e6a40068a8
Revises: 47ba782fb318
Create Date: 2024-03-27 21:04:24.874658

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "07e6a40068a8"
down_revision = "47ba782fb318"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userprojectmodel",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("faculty_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["faculty_id"],
            ["facultymodel.faculty_id"],
        ),
        sa.PrimaryKeyConstraint("project_id"),
    )
    op.create_index(
        op.f("ix_userprojectmodel_project_id"), "userprojectmodel", ["project_id"], unique=False
    )
    op.create_table(
        "userprojectlinkmodel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("user_project_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accountmodel.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_project_id"],
            ["userprojectmodel.project_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usertaskmodel",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("reviewer", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("task_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["userprojectmodel.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer"],
            ["accountmodel.account_id"],
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_index(op.f("ix_usertaskmodel_task_id"), "usertaskmodel", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usertaskmodel_task_id"), table_name="usertaskmodel")
    op.drop_table("usertaskmodel")
    op.drop_table("userprojectlinkmodel")
    op.drop_index(op.f("ix_userprojectmodel_project_id"), table_name="userprojectmodel")
    op.drop_table("userprojectmodel")
    # ### end Alembic commands ###
