"""Task state

Revision ID: 13b56ccfb196
Revises: 1c0a97691b8d
Create Date: 2024-04-02 14:31:36.061662

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "13b56ccfb196"
down_revision = "1c0a97691b8d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    enum = sa.Enum("OPEN", "RESUBMIT", "IN_PROGRESS", "IN_REVIEW", "DONE", name="taskstate")
    enum.create(op.get_bind())
    op.add_column(
        "usertaskmodel",
        sa.Column(
            "state",
            enum,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_usertaskmodel_project_id"), "usertaskmodel", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_usertaskmodel_state"), "usertaskmodel", ["state"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usertaskmodel_state"), table_name="usertaskmodel")
    op.drop_index(op.f("ix_usertaskmodel_project_id"), table_name="usertaskmodel")
    op.drop_column("usertaskmodel", "state")
    # ### end Alembic commands ###
