"""Add Unique constraint

Revision ID: 3e8c5ae32580
Revises: 122480cc7adf
Create Date: 2024-04-04 19:41:40.289910

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "3e8c5ae32580"
down_revision = "122480cc7adf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_commentmodel_comment_id", table_name="commentmodel")
    op.create_index(op.f("ix_commentmodel_comment_id"), "commentmodel", ["comment_id"], unique=True)
    op.create_foreign_key(None, "commentmodel", "filemodel", ["file_id"], ["file_id"])
    op.drop_index("ix_userprojectmodel_project_id", table_name="userprojectmodel")
    op.create_index(
        op.f("ix_userprojectmodel_project_id"), "userprojectmodel", ["project_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_userprojectmodel_project_id"), table_name="userprojectmodel")
    op.create_index(
        "ix_userprojectmodel_project_id", "userprojectmodel", ["project_id"], unique=False
    )
    op.drop_constraint(None, "commentmodel", type_="foreignkey")
    op.drop_index(op.f("ix_commentmodel_comment_id"), table_name="commentmodel")
    op.create_index("ix_commentmodel_comment_id", "commentmodel", ["comment_id"], unique=False)
    # ### end Alembic commands ###
