"""Project and Task models

Revision ID: 47ba782fb318
Revises: 9f098bdc161f
Create Date: 2024-03-27 20:39:09.316889

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "47ba782fb318"
down_revision = "9f098bdc161f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projectmodel",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("faculty_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["faculty_id"],
            ["facultymodel.faculty_id"],
        ),
        sa.PrimaryKeyConstraint("project_id"),
    )
    op.create_index(
        op.f("ix_projectmodel_project_id"), "projectmodel", ["project_id"], unique=False
    )
    op.create_table(
        "taskmodel",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("reviewer", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("task_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projectmodel.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer"],
            ["accountmodel.account_id"],
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_index(op.f("ix_taskmodel_project_id"), "taskmodel", ["project_id"], unique=False)
    op.create_index(op.f("ix_taskmodel_task_id"), "taskmodel", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_taskmodel_task_id"), table_name="taskmodel")
    op.drop_index(op.f("ix_taskmodel_project_id"), table_name="taskmodel")
    op.drop_table("taskmodel")
    op.drop_index(op.f("ix_projectmodel_project_id"), table_name="projectmodel")
    op.drop_table("projectmodel")
    # ### end Alembic commands ###
