"""Add Unique Contrsint

Revision ID: 7d1b0a6a4a73
Revises: dbb9e7944923
Create Date: 2024-03-25 19:23:34.287811

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "7d1b0a6a4a73"
down_revision = "dbb9e7944923"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "faculty_name_department_unique_constraint", "facultymodel", ["name", "department_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("faculty_name_department_unique_constraint", "facultymodel", type_="unique")
    # ### end Alembic commands ###
