"""Account Type Field

Revision ID: 7fba93c32d29
Revises: 7eb86db6437c
Create Date: 2024-03-16 11:59:08.676006

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7fba93c32d29"
down_revision = "7eb86db6437c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    enum = sa.Enum("ADMIN", "STUDENT", "TEACHER", "OVERSEER", name="accounttype")
    enum.create(op.get_bind())
    op.add_column(
        "accountmodel",
        sa.Column(
            "account_type",
            enum,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accountmodel", "account_type")
    # ### end Alembic commands ###
