"""Add email codes

Revision ID: b45b88ba10c3
Revises: 25983dc20be6
Create Date: 2024-05-23 17:14:53.390922

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "b45b88ba10c3"
down_revision = "25983dc20be6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "emailcodemodel",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email_code_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("account_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("code_type", sa.Enum("RESET_PASSWORD", name="emailcodetype"), nullable=False),
        sa.Column("hashed_code_value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("expiration_date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accountmodel.account_id"],
        ),
        sa.PrimaryKeyConstraint("email_code_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("emailcodemodel")
    # ### end Alembic commands ###
