"""Email Confirmation Code

Revision ID: dbb9e7944923
Revises: 7fba93c32d29
Create Date: 2024-03-16 14:05:56.682227

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "dbb9e7944923"
down_revision = "7fba93c32d29"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registrationemailcode",
        sa.Column("account_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accountmodel.account_id"],
        ),
        sa.PrimaryKeyConstraint("account_id"),
        sa.UniqueConstraint("code"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("registrationemailcode")
    # ### end Alembic commands ###
