"""Communication init 2

Revision ID: e24ff83b92a7
Revises: ec950cb7bb00
Create Date: 2024-04-10 16:26:21.196025

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "e24ff83b92a7"
down_revision = "ec950cb7bb00"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chataccountlinkmodel",
        sa.Column("account_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("chat_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accountmodel.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chatmodel.chat_id"],
        ),
        sa.PrimaryKeyConstraint("account_id", "chat_id"),
    )
    op.create_table(
        "messageseenby",
        sa.Column("account_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("message_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("at_time", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accountmodel.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messagemodel.message_id"],
        ),
        sa.PrimaryKeyConstraint("account_id", "message_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messageseenby")
    op.drop_table("chataccountlinkmodel")
    # ### end Alembic commands ###
