"""Add cascade argument for cooments

Revision ID: e966c95d7210
Revises: a1b85513c68b
Create Date: 2024-05-20 17:35:01.567525

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e966c95d7210"
down_revision = "a1b85513c68b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("commentmodel", "sender_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint("commentmodel_sender_id_fkey", "commentmodel", type_="foreignkey")
    op.create_foreign_key(
        None, "commentmodel", "accountmodel", ["sender_id"], ["account_id"], ondelete="CASCADE"
    )
    op.alter_column("usertaskmodel", "project_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint("usertaskmodel_project_id_fkey", "usertaskmodel", type_="foreignkey")
    op.create_foreign_key(
        None,
        "usertaskmodel",
        "userprojectmodel",
        ["project_id"],
        ["project_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "usertaskmodel", type_="foreignkey")
    op.create_foreign_key(
        "usertaskmodel_project_id_fkey",
        "usertaskmodel",
        "userprojectmodel",
        ["project_id"],
        ["project_id"],
    )
    op.alter_column("usertaskmodel", "project_id", existing_type=sa.UUID(), nullable=False)
    op.drop_constraint(None, "commentmodel", type_="foreignkey")
    op.create_foreign_key(
        "commentmodel_sender_id_fkey", "commentmodel", "accountmodel", ["sender_id"], ["account_id"]
    )
    op.alter_column("commentmodel", "sender_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
