"""Communication init

Revision ID: ec950cb7bb00
Revises: 3e8c5ae32580
Create Date: 2024-04-08 17:06:55.637622

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "ec950cb7bb00"
down_revision = "3e8c5ae32580"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chatmodel",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("chat_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    op.create_table(
        "messagemodel",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("file_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("message_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("sender_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("chat_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chatmodel.chat_id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["filemodel.file_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["accountmodel.account_id"],
        ),
        sa.PrimaryKeyConstraint("message_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messagemodel")
    op.drop_table("chatmodel")
    # ### end Alembic commands ###
