name: Run Docker Compose
on:
  push:
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
