name: Run Docker Compose
on:
  workflow_run:
    workflows: ["Create Docker Image for release"]
    types:
      - completed
  workflow_dispatch:

jobs:
  docker:
    runs-on: self-hosted

    steps:

    - name: Fetch new images (nginx)
      run: docker pull ghcr.io/wandering-cursor/samurai-nginx:latest
    - name: Fetch new images (worker)
      run: docker pull ghcr.io/wandering-cursor/samurai-worker:latest
    - name: Fetch new images (backend)
      run: docker pull ghcr.io/wandering-cursor/samurai-backend:latest
    - name: Fetch new images (beat)
      run: docker pull ghcr.io/wandering-cursor/samurai-beat:latest

    - name: Stop containers
      run: docker compose -f "docker-compose.yml" down

    - name: Checkout
      uses: actions/checkout@v4
      with:
        clean: false

    - name: Create secret files
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
        echo "${{ secrets.NGINX_FILE }}" > nginx.conf

    - name: Start containers
      run: docker compose -f "docker-compose.yml" up -d --build
