name: Run Docker Compose
on:
  workflow_run:
    workflows: ["Create Docker Image for release"]
    types:
      - completed
  workflow_dispatch:

jobs:
  stop-containers:
    runs-on: self-hosted

    steps:
      - name: Stop containers
        run: docker compose -f "compose/prod-docker-compose.yml" down

  start-containers:
    if: always()
    needs: stop-containers
    runs-on: self-hosted

    steps:
      - name: Log In
        run: echo "${{ secrets.PACKAGES_PAT }}" | docker login ghcr.io -u Wandering-Cursor --password-stdin

      - name: Fetch new images (backend)
        run: docker pull ghcr.io/wandering-cursor/samurai-backend:latest

      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false
      
      - name: PWD + LS
        run: |
          echo $(pwd)
          echo $(ls -a)

      - name: Create secret files
        run: |
          echo "${{ secrets.settings_env }}" > compose/.secrets/settings_env
          echo "${{ secrets.security_env }}" > compose/.secrets/settings_env
          echo "${{ secrets.POSTGRES_DB }}" > compose/.secrets/POSTGRES_DB
          echo "${{ secrets.POSTGRES_USER }}" > compose/.secrets/POSTGRES_USER
          echo "${{ secrets.POSTGRES_PASSWORD }}" > compose/.secrets/POSTGRES_PASSWORD

      - name: Start containers
        run: docker compose -f "compose/prod-docker-compose.yml" up -d
