name: Run lint checks on code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  lint-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r lint-requirements.txt

    - name: Run isort and ruff in check-only mode
      run: |
        isort --check-only .
        ruff check .

