# Since there are multiple dockerfiles in the project, we need to push all of them to github container registry
name: Create Docker Image for release

on:
    release:
        types: [released]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        # Setup matrix for dockerfiles
        strategy:
            fail-fast: false
            matrix:
                include:
                    -
                        dockerfile: backend.dockerfile
                        tag: ghcr.io/wandering-cursor/samurai-backend
                    -
                        dockerfile: beat.dockerfile
                        tag: ghcr.io/wandering-cursor/samurai-beat
                    -
                        dockerfile: worker.dockerfile
                        tag: ghcr.io/wandering-cursor/samurai-worker
                    -
                        dockerfile: nginx.dockerfile
                        tag: ghcr.io/wandering-cursor/samurai-nginx
        steps:
            -
                name: Checkout
                uses: actions/checkout@v4
            -
                name: Login to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -
                name: Create secret files (Empty for now. Relace with real ones in production)
                run: |
                    echo "" > .env
                    echo "" > nginx.conf
            -
                name: Build and push the images
                uses: docker/build-push-action@v4
                with:
                    context: .
                    file: ${{ matrix.dockerfile }}
                    tags: ${{ matrix.tag }}
                    push: true
            

        