name: Create Docker Image for release

on:
    release:
        types: [released]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        # Setup matrix for docker images
        strategy:
            fail-fast: false
            matrix:
                include:
                    - dockerfile: Dockerfile
                      tag: ghcr.io/wandering-cursor/samurai-backend
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push the images
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ${{ matrix.dockerfile }}
                  tags: ${{ matrix.tag }}
                  push: true
